drop_pepsicocas:
    test:
        global: true
drop_more_pepsicocas:
    test:
        users: user1, user2, user3
        groups: group1, group2
    test2:
        users: userA, userB, userC
        groups: groupA, groupB
